name: pytest-default

on: pull_request

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up uv
        run: curl -LsSf https://astral.sh/uv/0.3.0/install.sh | sh
      - name: Set up Python
        run: uv python install 3.9
      - name: Install the project
        run: |
          uv venv && source .venv/bin/activate
          uv pip install --index-url https://download.pytorch.org/whl/cpu torch==2.4.0+cpu torchvision==0.19.0+cpu torchaudio==2.4.0+cpu
          uv pip install -r pyproject.toml --extra dev --override uv_overrides.txt
      - name: Uninstall the old asdfghjkl if exists
        run: uv pip uninstall asdfghjkl-old
      - name: Test without the old asdfghjkl
        run: |
          source .venv/bin/activate
          python3 -m pytest tests
